language: R
cache: packages
sudo: false
warnings_are_errors: false # true

addons:
  apt:
    packages:
      # - libgsl0-dev # for topicmodels
      # - libxml2-dev # for XML, a dependency of quanteda

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
