# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

# warnings_are_errors: true

# addons:
#   apt:
#     packages:
#       - libgsl0-dev # for topicmodels
#       - libxml2-dev # for XML, a dependency of quanteda

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
